/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xlang;

import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        if (args.length != 1) {
            return;
        }
        var path = args[0];
        new Xlang().execute(Paths.get(path));
    }
}
